### ISSUE TITLE
The use of DMULTITHREAD

### ISSUE THREAD

**Issue by ilya1725** [eembc/coremark#13]
Hello:

What is the point of `-DMULTITHREAD`? I've tried running the benchmark on my system with this flag set to 1,2,4,16 and getting the same results.
However, the more complex underlined question is how CoreMarks takes into account multiple cores? There is nothing about it in the README or the EEMBC whitepaper.

Thank you.

**Comment by benjaminogles** [comment]
You also have to specify which multithread implementation to use.
`-DUSE_PTHREAD=1` or `-DUSE_FORK=1` or `-DUSE_SOCKET=1` are the options I think.

**Comment by ilya1725** [comment]
I used `-DUSE_FORK=1`. Same result.

**Comment by petertorelli** [comment]
`MULTITHREAD=N` enables code for parallel execution, where the value of `N` determines the number of instances. The parallel implementation may be `USE_(FORK|PTHREAD|SOCKET)=1`. The implementation is defined in the `core_portme.c` file for the particular platform using the two functions `core_start_parallel` and `core_stop_parallel`. The `linux` and `linux64` targets both implement all three modes with example code. Here is a `pthreads` example: https://github.com/eembc/coremark/blob/2e9d6165f362f7071d29b7f88c6d32655e5d4a3c/linux64/core_portme.c#L236-L243

Example:
```
$ make PORT_DIR=macOS
$ grep "Iterations/Sec" run2.log
Iterations/Sec   : 19559.264572
$ make PORT_DIR=macOS clean
$ make PORT_DIR=macOS XCFLAGS='-DMULTITHREAD=4 -DUSE_PTHREAD'
$ grep "Iteration/Sec" run2.log
Iterations/Sec   : 71577.691619
```

**Comment by crown-hg** [comment]
I had the same problem @ilya1725 had. My solution is to delete coremark.exe every time I run `make XCFLAGS='-DMULTITHREAD=4 -DUSE_PTHREAD'`

**Comment by rafi-kamal** [comment]
I am also having the same issue in Debian. I have to do `make clean` after every run, otherwise only a single thread gets used.
