### ISSUE TITLE
Ensure prototypes are valid C

### ISSUE THREAD

**Issue by craben20** [eembc/coremark#14]
https://github.com/eembc/coremark/blob/2e9d6165f362f7071d29b7f88c6d32655e5d4a3c/coremark.h#L78

Unlike C++, this function isn't recognised as a valid function prototype - it may take 0 or n arguments. To avoid warnings, this line should be replaced with 
```c
ee_u8 check_data_types(void);
```

**Comment by petertorelli** [comment]
Updated. Thanks.

**Comment by jrtc27** [comment]
Please also update coremark.md5 to reflect this change.

**Comment by petertorelli** [comment]
@jrtc27 Good catch. Thanks.
