### ISSUE TITLE
Question regarding type `ee_f16`

### ISSUE THREAD

**Issue by JOE1994** [eembc/coremark#16]
Hello, I noticed that there is no type definition provided for `ee_f16` inside the project (although it is used to define type `MATDAT` ). `core_portme.h`, which contains definitions for most of the `ee_~` types doesn't contain definition for `ee_f16`. Are benchmark users expected to provide their own implementation and definition for `ee_f16` to run the benchmark with `ee_f16` ? Thank you 🤓 

https://github.com/eembc/coremark/blob/21d473aae1f11d52ea592a8685734be2209aa66f/coremark.h#L103-L110

**Comment by petertorelli** [comment]
Hi @JOE1994,
This is dead code as the floating-point matrix multiply was never activated in production. Given the fact that there is no standard C way of defining a 16-bit float, it would require, as you pointed out, a user-specific definition for that platform.
Thanks,
Peter
