### ISSUE TITLE
Link failed for barebone porting

### ISSUE THREAD

**Issue by ShawnLess** [eembc/coremark#2]
Hey Guys:
Thanks for this helpful benchmark! It's way more easy to read and port then Drystone. 
Anywhere, when I tried to port to our bare mental RISC-V core, I found following issues may need to fixed:
# size_t is missing 
I believed the 'size_t' is defined in <stddef.h> which is Linux only? for bare mental cores, we need to add a definition for that. My work around is adding following line to [barebones/core_portme.h](
https://github.com/ShawnLess/coremark/commit/a748a7e751ab0db9a0f5536a8aac01a81e2455fb#diff-e99350073de3b499b9a7d88d9fe81647)

```c
#define size_t long
``` 

# CLOCKS_PER_SEC is missing 
Also need to add the definition to [barebones/core_portme.h](
https://github.com/ShawnLess/coremark/commit/a748a7e751ab0db9a0f5536a8aac01a81e2455fb#diff-e99350073de3b499b9a7d88d9fe81647)

# PORT_OBJS is missing 
We have defined PORT_SRCS in **barebones/core_portme.mak**, but did not define PORT_OBJS which is also referenced in top Makefile.

# HAS_FLOAT macros check.
In **coremark/barebones/core_portme.h** we have following configuration switches:
```c
/* Configuration : HAS_FLOAT 
	Define to 1 if the platform supports floating point.
*/
#ifndef HAS_FLOAT 
#define HAS_FLOAT 1
#endif
```
But we only checks if the **HAS_FLOAT** defined or not, which is not right because the macros is always defined, but with different values. 

We may need to check the macro value other than only check the definition in **barebones/ee_printf.c**:
```c
#if(HAS_FLOAT==1)
...
#endif
```
After the aforementioned work around, I was able to compile & link the barebone porting with RISC-V toolchains (https://github.com/ShawnLess/coremark).

**Comment by petertorelli** [comment]
CoreMark was not written with automake/configure checks, and as such, there may be instances when a compiler does not properly support an ISO standard, like `size_t`, and will require manual modifications.

CLOCKS_PER_SEC is left as a default case; if it is set to a wrong default value, it will cause soft-errors. Perhaps a pragma would make more sense than defining it to a bogus value?

PORT_OBJS omission was an oversight.

HAS_FLOAT mismatch was an oversight, nowhere is it checked for value, only if/ifndef.

Thanks for the feedback. Glad to hear it was ported to RISC-V!

**Comment by ShawnLess** [comment]
Hey Peter:

Thanks for the response.

We are trying to port the benchmark on Celerity: [The Celerity Open-Source 511-Core RISC-V Tiered Accelerator Fabric: Fast Architectures and Design Methodologies for Fast Chips](https://ieeexplore.ieee.org/document/8344478/), which is a manycore architecture. 

The biggest challenge for us is how to offload and split the tasks on the manycore tile. 

Looking forward to the code enhancement!

**Comment by petertorelli** [comment]
Hi @ShawnLess,
Finally carving out some time to address issues. Can you generate a pull request from your repo that fixes the barebones issues?
Thanks!
Peter

**Comment by petertorelli** [comment]
Left open after merge occurred. Closing.
