### ISSUE TITLE
Amateur asking for help regarding ARM architectures (THIS IS NOT AN ISSUE)

### ISSUE THREAD

**Issue by sadunhaq123** [eembc/coremark#24]
Hi,

I am a newbie, trying to use coremark benchmarks for Raspberry Pi 4. I have never run any benchmarks without GUI interface, so I am having difficulties using the 'run' command. Can you give a small example, on how to use the 'run' command? I have googled it and I did not find any helpful examples. I may be missing something simple, as everyone else seems to be getting it (as there aren't much examples). This is not really an issue, but I could not find, where to ask for help.

Thank You.

**Comment by petertorelli** [comment]
Compilation and execution are contained in the makefile. I suggest you study how to use [`make`](https://www.gnu.org/software/make/), which is the primary build system of the vast majority of C projects.
