### ISSUE TITLE
Makefile:44: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by Frankccv** [eembc/coremark#33]
I run the command make and this is the error:
Makefile:44: *** missing separator.  Stop.
Line 44 : $(error PLEASE define PORT_DIR! (e.g. make PORT_DIR=simple))

**Comment by petertorelli** [comment]
You need to specify a folder containing the port files explained in the README. The makefile tries to autodetect your system, and if it cannot, it falls back to the user-specified PORT_DIR.

**Comment by petertorelli** [comment]
Closing due to no response.
