### ISSUE TITLE
Error while running the coremark with gcc 

### ISSUE THREAD

**Issue by waseemabbas-10xe** [eembc/coremark#59]
When I run this command in terminal to run the coremark:
gcc -O2 -o coremark.exe core_list_join.c core_main.c core_matrix.c core_state.c core_util.c simple/core_portme.c -DPERFORMANCE_RUN=1 -DITERATIONS=1000
Please let us know in which directory we have to run this command that you have mention in Readme file.
![image](https://github.com/eembc/coremark/assets/142871238/4687a6dd-1ea0-43b5-9024-e6552562efd2)

**Comment by sergiocaballeroo** [comment]
you solved the error? same issue in Windows Server
![error](https://github.com/user-attachments/assets/3724d506-bc27-436c-bb7c-2cb5e44a2956)

**Comment by waseemabbas-10xe** [comment]
Can you please add the path of these files where these are present so this error will be removed.
